# Generated by Django 5.0.14 on 2026-02-10 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this assignment automatically expires')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.page')),
                ('resource', models.ForeignKey(limit_choices_to={'role': 'RESOURCE'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docpro_assignment',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['status', 'resource'], name='docpro_assi_status_6327ec_idx'), models.Index(fields=['status', 'expires_at'], name='docpro_assi_status_64e07c_idx')],
            },
        ),
    ]
