# Generated by Django 5.0.14 on 2026-02-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_delete_documentassignment'),
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='combined_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/combined/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.document'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='end_page',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_page',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.page'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('FAILED', 'Failed')], default='ACTIVE', max_length=20),
        ),
    ]
