# Generated by Django 5.0.14 on 2026-02-17 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_delete_documentassignment'),
        ('processing', '0002_assignment_combined_file_assignment_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed')], default='WAITING', max_length=20)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Queue',
                'verbose_name_plural': 'Document Queue',
                'db_table': 'docpro_queue',
                'ordering': ['created_at'],
            },
        ),
    ]
