# Generated by Django 5.0.14 on 2026-02-24 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_page_version_page_docpro_page_documen_a90ec6_idx'),
        ('processing', '0003_documentqueue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['document', 'status'], name='docpro_assi_documen_e96d10_idx'),
        ),
    ]
