# Generated by Django 5.0.14 on 2026-02-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_assignment_docpro_assi_documen_e96d10_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
