# Generated by Django 5.0.14 on 2026-02-25 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_page_is_locked_alter_document_status'),
        ('processing', '0005_assignment_viewed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='WAITING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['WAITING', 'PROCESSING', 'COMPLETED'])), fields=('document', 'start_page', 'end_page'), name='unique_assignment_range'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['WAITING', 'PROCESSING'])), fields=('document', 'resource'), name='unique_resource_document'),
        ),
    ]
