# Generated by Django 6.0.2 on 2026-03-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0007_remove_assignment_unique_assignment_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='sla_breached',
            field=models.BooleanField(default=False),
        ),
    ]
