# Generated by Django 6.0.2 on 2026-03-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0008_assignment_sla_breached'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='processed_file',
            field=models.FileField(blank=True, help_text='The generated result PDF after resource submission.', null=True, upload_to='assignments/processed/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='combined_file',
            field=models.FileField(blank=True, help_text='The split source PDF for the resource to work on.', null=True, upload_to='assignments/combined/%Y/%m/%d/'),
        ),
    ]
