# Generated by Django 6.0.2 on 2026-03-03 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_document_is_deleted'),
        ('processing', '0009_assignment_processed_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_content', models.TextField(blank=True, null=True)),
                ('after_content', models.TextField(blank=True, null=True)),
                ('before_layout', models.JSONField(blank=True, null=True)),
                ('after_layout', models.JSONField(blank=True, null=True)),
                ('suggestions_applied', models.JSONField(default=list, help_text='List of NLP suggestions applied in this revision')),
                ('user_overrides', models.JSONField(default=list, help_text='List of validation overrides made by the user')),
                ('is_nlp_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.page')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docpro_revision_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
