# Generated by Django 6.0.2 on 2026-03-05 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_resourceprofile_docpro_reso_is_acti_c2c01b_idx_and_more'),
        ('documents', '0024_approveddocument_mergeddocument_originaldocument_and_more'),
        ('processing', '0010_revisionhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('QUALITY_FAILED', 'Quality Failed'), ('REASSIGNED', 'Reassigned'), ('TIMED_OUT', 'Timed Out'), ('UNASSIGNED', 'Unassigned'), ('ESCALATED', 'Escalated')], db_index=True, default='ASSIGNED', max_length=20)),
                ('edited_blocks_json', models.JSONField(default=list)),
                ('resource_notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('processing_start_at', models.DateTimeField(blank=True, null=True)),
                ('processing_end_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration', models.DurationField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('max_processing_time', models.IntegerField(default=600)),
                ('time_warning_sent', models.BooleanField(default=False)),
                ('timed_out', models.BooleanField(default=False)),
                ('timed_out_at', models.DateTimeField(blank=True, null=True)),
                ('reassignment_count', models.IntegerField(default=0)),
                ('is_reassigned', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'page_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ReassignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reassigned_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=50)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'reassignment_logs',
            },
        ),
        migrations.CreateModel(
            name='RejectedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('rejection_reason', models.CharField(choices=[('QUALITY_FAIL', 'Quality Below Standard'), ('INCOMPLETE', 'Incomplete Processing'), ('INCORRECT_DATA', 'Incorrect Data Entry'), ('FORMATTING_ERROR', 'Formatting Errors'), ('MISSING_CONTENT', 'Missing Content'), ('OCR_ERROR', 'OCR Error Unresolved'), ('MANUAL_OVERRIDE', 'Admin Manual Rejection')], max_length=20)),
                ('rejection_notes', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reassign_status', models.CharField(choices=[('IN_QUEUE', 'In Reassignment Queue'), ('REASSIGNING', 'Being Reassigned'), ('REASSIGNED', 'Reassigned Successfully'), ('ESCALATED', 'Escalated — Max Attempts'), ('CANCELLED', 'Cancelled')], db_index=True, default='IN_QUEUE', max_length=15)),
                ('rejection_count', models.IntegerField(default=1)),
                ('max_rejections', models.IntegerField(default=3)),
                ('queue_position', models.IntegerField(default=0)),
                ('reassigned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rejected_pages',
                'ordering': ['queue_position', '-rejected_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmittedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_text', models.TextField(blank=True)),
                ('edited_blocks_json', models.JSONField(default=list)),
                ('output_page_file', models.FileField(blank=True, max_length=500, null=True, upload_to='submitted_pages/%Y/%m/%d/')),
                ('resource_notes', models.TextField(blank=True)),
                ('page_number', models.IntegerField()),
                ('processing_duration', models.DurationField(blank=True, null=True)),
                ('processing_start_at', models.DateTimeField(blank=True, null=True)),
                ('processing_end_at', models.DateTimeField(blank=True, null=True)),
                ('words_processed', models.IntegerField(default=0)),
                ('blocks_edited', models.IntegerField(default=0)),
                ('blocks_total', models.IntegerField(default=0)),
                ('review_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Admin Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING_REVIEW', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'submitted_pages',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='docpro_assi_status_6327ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='docpro_assi_status_64e07c_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='docpro_assi_documen_e96d10_idx',
        ),
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_resource_document',
        ),
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_assignment_range',
        ),
        migrations.RemoveField(
            model_name='revisionhistory',
            name='page',
        ),
        migrations.RemoveField(
            model_name='revisionhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='pageassignment',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.splitpage'),
        ),
        migrations.AddField(
            model_name='pageassignment',
            name='reassigned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_to', to='processing.pageassignment'),
        ),
        migrations.AddField(
            model_name='pageassignment',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_assignments', to='accounts.resourceprofile'),
        ),
        migrations.AddField(
            model_name='reassignmentlog',
            name='new_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignment_source', to='processing.pageassignment'),
        ),
        migrations.AddField(
            model_name='reassignmentlog',
            name='new_resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gained_assignments_logs', to='accounts.resourceprofile'),
        ),
        migrations.AddField(
            model_name='reassignmentlog',
            name='original_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignment_history', to='processing.pageassignment'),
        ),
        migrations.AddField(
            model_name='reassignmentlog',
            name='previous_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_assignments_logs', to='accounts.resourceprofile'),
        ),
        migrations.AddField(
            model_name='reassignmentlog',
            name='reassigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rejectedpage',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_pages', to='documents.originaldocument'),
        ),
        migrations.AddField(
            model_name='rejectedpage',
            name='excluded_resources',
            field=models.ManyToManyField(blank=True, related_name='excluded_from_rejections', to='accounts.resourceprofile'),
        ),
        migrations.AddField(
            model_name='rejectedpage',
            name='new_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_rejection', to='processing.pageassignment'),
        ),
        migrations.AddField(
            model_name='rejectedpage',
            name='original_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rejections_received', to='accounts.resourceprofile'),
        ),
        migrations.AddField(
            model_name='rejectedpage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='documents.splitpage'),
        ),
        migrations.AddField(
            model_name='rejectedpage',
            name='reassigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_rejections', to='accounts.resourceprofile'),
        ),
        migrations.AddField(
            model_name='rejectedpage',
            name='rejected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rejected_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submittedpage',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='processing.pageassignment'),
        ),
        migrations.AddField(
            model_name='submittedpage',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_pages', to='documents.originaldocument'),
        ),
        migrations.AddField(
            model_name='submittedpage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='documents.splitpage'),
        ),
        migrations.AddField(
            model_name='submittedpage',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submittedpage',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rejectedpage',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='processing.submittedpage'),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='document',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='page',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='resource',
        ),
        migrations.DeleteModel(
            name='DocumentQueue',
        ),
        migrations.DeleteModel(
            name='RevisionHistory',
        ),
        migrations.AddIndex(
            model_name='pageassignment',
            index=models.Index(fields=['page', 'status'], name='page_assign_page_id_c9a009_idx'),
        ),
        migrations.AddIndex(
            model_name='pageassignment',
            index=models.Index(fields=['resource', 'status'], name='page_assign_resourc_17f5df_idx'),
        ),
        migrations.AddIndex(
            model_name='pageassignment',
            index=models.Index(fields=['status', 'processing_start_at'], name='page_assign_status_f2fec6_idx'),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
