# Generated by Django 6.0.2 on 2026-03-05 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_document_documentversion_page_and_more'),
        ('processing', '0011_pageassignment_reassignmentlog_rejectedpage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page', models.PositiveIntegerField(null=True)),
                ('end_page', models.PositiveIntegerField(null=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('combined_file', models.FileField(blank=True, help_text='The split source PDF for the resource to work on.', null=True, upload_to='assignments/combined/%Y/%m/%d/')),
                ('processed_file', models.FileField(blank=True, help_text='The generated result PDF after resource submission.', null=True, upload_to='assignments/processed/%Y/%m/%d/')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this assignment automatically expires')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('REJECTED', 'Rejected')], default='WAITING', max_length=20)),
                ('sla_breached', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'docpro_assignment',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed')], default='WAITING', max_length=20)),
            ],
            options={
                'verbose_name': 'Document Queue',
                'verbose_name_plural': 'Document Queue',
                'db_table': 'docpro_queue',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_content', models.TextField(blank=True, null=True)),
                ('after_content', models.TextField(blank=True, null=True)),
                ('before_layout', models.JSONField(blank=True, null=True)),
                ('after_layout', models.JSONField(blank=True, null=True)),
                ('suggestions_applied', models.JSONField(default=list, help_text='List of NLP suggestions applied in this revision')),
                ('user_overrides', models.JSONField(default=list, help_text='List of validation overrides made by the user')),
                ('is_nlp_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'docpro_revision_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='pageassignment',
            name='page_assign_page_id_c9a009_idx',
        ),
        migrations.RemoveIndex(
            model_name='pageassignment',
            name='page_assign_resourc_17f5df_idx',
        ),
        migrations.RemoveIndex(
            model_name='pageassignment',
            name='page_assign_status_f2fec6_idx',
        ),
        migrations.RemoveField(
            model_name='rejectedpage',
            name='new_assignment',
        ),
        migrations.RemoveField(
            model_name='submittedpage',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='rejectedpage',
            name='document',
        ),
        migrations.RemoveField(
            model_name='rejectedpage',
            name='excluded_resources',
        ),
        migrations.RemoveField(
            model_name='rejectedpage',
            name='original_resource',
        ),
        migrations.RemoveField(
            model_name='rejectedpage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='rejectedpage',
            name='reassigned_to',
        ),
        migrations.RemoveField(
            model_name='rejectedpage',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='rejectedpage',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='submittedpage',
            name='document',
        ),
        migrations.RemoveField(
            model_name='submittedpage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='submittedpage',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='submittedpage',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='assignment',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.document'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.page'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='resource',
            field=models.ForeignKey(limit_choices_to={'role': 'RESOURCE'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentqueue',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='documents.document'),
        ),
        migrations.AddField(
            model_name='revisionhistory',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.page'),
        ),
        migrations.AddField(
            model_name='revisionhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pageassignment',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pageassignment',
            name='reassigned_from',
        ),
        migrations.RemoveField(
            model_name='pageassignment',
            name='resource',
        ),
        migrations.DeleteModel(
            name='ReassignmentLog',
        ),
        migrations.DeleteModel(
            name='RejectedPage',
        ),
        migrations.DeleteModel(
            name='SubmittedPage',
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['document', 'status'], name='docpro_assi_documen_e96d10_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'resource'], name='docpro_assi_status_6327ec_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'expires_at'], name='docpro_assi_status_64e07c_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['WAITING', 'PROCESSING'])), fields=('document', 'start_page', 'end_page'), name='unique_assignment_range'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['WAITING', 'PROCESSING'])), fields=('document', 'resource'), name='unique_resource_document'),
        ),
        migrations.DeleteModel(
            name='PageAssignment',
        ),
    ]
