# Generated by Django 6.0.2 on 2026-03-05 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_document_conversion_status_document_original_format_and_more'),
        ('processing', '0012_assignment_documentqueue_revisionhistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_processing_time',
            field=models.IntegerField(default=600, help_text='Maximum allowed time in seconds'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reassignment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='time_warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='timed_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('PROCESSING', 'Processing'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('REJECTED', 'Rejected'), ('QUALITY_FAILED', 'Quality Failed'), ('REASSIGNED', 'Reassigned'), ('TIMED_OUT', 'Timed Out'), ('UNASSIGNED', 'Unassigned'), ('ESCALATED', 'Escalated')], default='WAITING', max_length=20),
        ),
        migrations.CreateModel(
            name='PageValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField()),
                ('checks', models.JSONField(help_text='{ check_name: {passed, message} }')),
                ('error_detail', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='documents.page')),
            ],
            options={
                'db_table': 'docpro_page_validation',
            },
        ),
        migrations.CreateModel(
            name='ReassignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reassigned_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('QUALITY_FAIL', 'Quality below standard'), ('INCOMPLETE', 'Incomplete processing'), ('INCORRECT_DATA', 'Incorrect data entry'), ('FORMATTING_ERROR', 'Formatting errors'), ('TIMEOUT', 'Processing timeout'), ('MANUAL_OVERRIDE', 'Admin manual reassignment')], max_length=50)),
                ('admin_notes', models.TextField(blank=True)),
                ('new_assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_from', to='processing.assignment')),
                ('new_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gained_assignments', to=settings.AUTH_USER_MODEL)),
                ('original_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments', to='processing.assignment')),
                ('previous_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_assignments', to=settings.AUTH_USER_MODEL)),
                ('reassigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docpro_reassignment_log',
            },
        ),
    ]
