# Generated by Django 6.0.2 on 2026-03-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0013_assignment_max_processing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reassignmentlog',
            name='new_assignment',
        ),
        migrations.RemoveField(
            model_name='reassignmentlog',
            name='new_resource',
        ),
        migrations.RemoveField(
            model_name='reassignmentlog',
            name='original_assignment',
        ),
        migrations.RemoveField(
            model_name='reassignmentlog',
            name='previous_resource',
        ),
        migrations.RemoveField(
            model_name='reassignmentlog',
            name='reassigned_by',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='reassignment_count',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_processing_time',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('REJECTED', 'Rejected')], default='WAITING', max_length=20),
        ),
        migrations.DeleteModel(
            name='PageValidation',
        ),
        migrations.DeleteModel(
            name='ReassignmentLog',
        ),
    ]
