# Generated by Django 6.0.2 on 2026-03-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0014_add_assignment_time_tracking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_resource_document',
        ),
    ]
