# Generated by Django 6.0.2 on 2026-03-05 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0017_alter_approveddocument_approved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reassignmentlog',
            name='reassigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignment_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rejectedpage',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
