# Generated by Django 6.0.2 on 2026-03-05 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_resource_availability'),
        ('processing', '0018_alter_reassignmentlog_reassigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageassignment',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_assignments', to='accounts.resourceprofile'),
        ),
        migrations.AlterField(
            model_name='reassignmentlog',
            name='previous_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_assignments', to='accounts.resourceprofile'),
        ),
        migrations.AlterField(
            model_name='rejectedpage',
            name='original_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections_received', to='accounts.resourceprofile'),
        ),
    ]
