# Generated by Django 6.0.2 on 2026-03-05 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_resource_availability'),
        ('processing', '0020_alter_submittedpage_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageassignment',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_assignments', to='accounts.resourceprofile'),
        ),
    ]
