# Generated by Django 6.0.2 on 2026-03-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_resource_availability'),
        ('documents', '0031_make_doc_ref_unique'),
        ('processing', '0021_alter_pageassignment_resource'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pageassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ASSIGNED', 'IN_PROGRESS'])), fields=('page',), name='unique_active_assignment'),
        ),
    ]
