# Generated by Django 6.0.2 on 2026-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0022_pageassignment_unique_active_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedpage',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('QUALITY_FAIL', 'Quality Below Standard'), ('INCOMPLETE', 'Incomplete Processing'), ('INCORRECT_DATA', 'Incorrect Data Entry'), ('FORMATTING_ERROR', 'Formatting Errors'), ('MISSING_CONTENT', 'Missing Content'), ('OCR_ERROR', 'OCR Error Unresolved'), ('MANUAL_OVERRIDE', 'Admin Manual Rejection'), ('TIMEOUT', 'Processing Timeout')], max_length=50, null=True),
        ),
    ]
