# Generated by Django 6.0.3 on 2026-03-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0023_submittedpage_rejection_reason'),
    ]

    operations = [
    ]
