# Generated by Django 5.0.14 on 2026-02-10 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ASSIGNED', 'Page Assigned'), ('COMPLETED', 'Page Completed'), ('EXPIRED', 'Assignment Expired'), ('REVOKED', 'Assignment Revoked'), ('REASSIGNED', 'Page Reassigned'), ('RESOURCE_CHANGE', 'Resource Status Change'), ('DOC_COMPLETED', 'Document Completed')], max_length=50)),
                ('entity_type', models.CharField(help_text='e.g. Document, Page', max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context for the event')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docpro_audit',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='docpro_audi_entity__d75d34_idx'), models.Index(fields=['event_type', 'timestamp'], name='docpro_audi_event_t_9d5fa7_idx')],
            },
        ),
    ]
