# Generated by Django 5.0.14 on 2026-02-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('ASSIGNED', 'Page Assigned'), ('COMPLETED', 'Page Completed'), ('EXPIRED', 'Assignment Expired'), ('REVOKED', 'Assignment Revoked'), ('REASSIGNED', 'Page Reassigned'), ('RESOURCE_CHANGE', 'Resource Status Change'), ('DOC_COMPLETED', 'Document Completed'), ('DOC_UPLOADED', 'Document Uploaded'), ('DOC_SPLIT', 'Document Split')], max_length=50),
        ),
    ]
