# Generated by Django 6.0.2 on 2026-03-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ASSIGNED', 'Page Assigned'), ('COMPLETED', 'Page Completed'), ('EXPIRED', 'Assignment Expired'), ('REVOKED', 'Assignment Revoked'), ('REASSIGNED', 'Page Reassigned'), ('RESOURCE_CHANGE', 'Resource Status Change'), ('DOC_COMPLETED', 'Document Completed'), ('DOC_REJECTED', 'Document Rejected'), ('DOC_DOWNLOADED', 'Document Downloaded'), ('DOC_UPLOADED', 'Document Uploaded'), ('DOC_SPLIT', 'Document Split'), ('ASSIGNMENT_REVOKED', 'Assignment Revoked')], max_length=50),
        ),
    ]
