# Generated by Django 5.0.14 on 2026-02-10 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/originals/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('SPLITTING', 'Splitting'), ('PROCESSING', 'Processing'), ('MERGING', 'Merging'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('final_file', models.FileField(blank=True, null=True, upload_to='documents/finals/%Y/%m/%d/')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docpro_client_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('content_file', models.FileField(upload_to='pages/splits/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, help_text='Timestamp when page was locked to a resource', null=True)),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='pages/processed/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_assignee', models.ForeignKey(blank=True, limit_choices_to={'role': 'RESOURCE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pages', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document')),
            ],
            options={
                'db_table': 'docpro_page',
                'ordering': ['document', 'page_number'],
                'indexes': [models.Index(fields=['status', 'locked_at'], name='docpro_page_status_9e122c_idx'), models.Index(fields=['current_assignee', 'status'], name='docpro_page_current_f30a57_idx')],
                'unique_together': {('document', 'page_number')},
            },
        ),
    ]
