# Generated by Django 5.0.14 on 2026-02-17 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_page', models.PositiveIntegerField(help_text='1-based start page index')),
                ('end_page', models.PositiveIntegerField(help_text='1-based end page index')),
                ('assigned_file', models.FileField(blank=True, null=True, upload_to='assignments/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.document')),
                ('resource', models.ForeignKey(limit_choices_to={'role': 'RESOURCE'}, on_delete=django.db.models.deletion.CASCADE, related_name='document_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docpro_document_assignment',
                'ordering': ['-created_at'],
            },
        ),
    ]
