# Generated by Django 5.0.14 on 2026-02-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentassignment',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/processed/%Y/%m/%d/'),
        ),
    ]
