# Generated by Django 5.0.14 on 2026-02-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentassignment_processed_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentassignment',
            name='assigned_file',
        ),
        migrations.RemoveField(
            model_name='documentassignment',
            name='processed_file',
        ),
        migrations.AddField(
            model_name='documentassignment',
            name='segment_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='documentassignment',
            name='end_page',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='documentassignment',
            name='start_page',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='documentassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
