# Generated by Django 5.0.14 on 2026-02-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_documentassignment_assigned_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentassignment',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
