# Generated by Django 5.0.14 on 2026-02-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documentassignment_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentassignment',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to='processed/%Y/%m/%d/'),
        ),
    ]
