# Generated by Django 5.0.14 on 2026-02-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentassignment_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentassignment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='documentassignment',
            name='processed_file',
        ),
        migrations.AlterField(
            model_name='documentassignment',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Total pages in this assignment block', null=True),
        ),
    ]
