# Generated by Django 5.0.14 on 2026-02-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_documentassignment_completed_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentAssignment',
        ),
    ]
