# Generated by Django 5.0.14 on 2026-02-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_delete_documentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='layout_data',
            field=models.JSONField(blank=True, help_text='Reconstructed layout bounding boxes and structure', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='text_content',
            field=models.TextField(blank=True, help_text='Raw extracted or edited text content', null=True),
        ),
    ]
