# Generated by Django 5.0.14 on 2026-02-24 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_page_layout_data_page_text_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Optimistic locking version'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['document', 'status', 'page_number'], name='docpro_page_documen_a90ec6_idx'),
        ),
    ]
