# Generated by Django 5.0.14 on 2026-02-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_page_version_page_docpro_page_documen_a90ec6_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SPLITTING', 'Splitting'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
    ]
