# Generated by Django 5.0.14 on 2026-02-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_page_is_locked_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SPLITTING', 'Splitting'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('REVIEWING', 'Reviewing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
    ]
