# Generated by Django 5.0.14 on 2026-02-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='complexity',
            field=models.CharField(choices=[('SIMPLE', 'Paragraph/Simple'), ('TABLE', 'Table-Heavy')], default='SIMPLE', max_length=20),
        ),
    ]
