# Generated by Django 5.0.14 on 2026-02-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_page_complexity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='complexity',
        ),
        migrations.AddField(
            model_name='page',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the resource submitted this page', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='processing_duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Total time spent processing this page in seconds'),
        ),
        migrations.AddField(
            model_name='page',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, help_text='When the resource first opened this page for editing', null=True),
        ),
    ]
