# Generated by Django 5.0.14 on 2026-02-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_remove_page_complexity_page_processing_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Whether this page has passed the validation requirements'),
        ),
        migrations.AddField(
            model_name='page',
            name='validation_errors',
            field=models.JSONField(blank=True, help_text='List of validation failures (upload issues, formatting errors, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SPLITTING', 'Splitting'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('REVIEWING', 'Reviewing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('FAILED_VALIDATION', 'Failed Validation')], default='UPLOADED', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('IMPROPERLY_PROCESSED', 'Improperly Processed')], default='PENDING', max_length=20),
        ),
    ]
