# Generated by Django 5.0.14 on 2026-02-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_page_is_validated_page_validation_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='complexity_score',
            field=models.FloatField(default=1.0, help_text='Weighted complexity score (e.g. 1.0 for simple, 2.5 for tables)'),
        ),
        migrations.AddField(
            model_name='page',
            name='complexity_type',
            field=models.CharField(choices=[('SIMPLE', 'Simple (Paragraphs)'), ('TABLE_HEAVY', 'Table-Heavy'), ('COMPLEX', 'Complex (Mixed/Dense)')], default='SIMPLE', max_length=20),
        ),
    ]
