# Generated by Django 5.0.14 on 2026-02-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_page_complexity_score_page_complexity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='processing_end_date',
            field=models.DateField(blank=True, help_text='Date when processing ended', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='processing_end_time',
            field=models.TimeField(blank=True, help_text='Time when processing ended', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='processing_start_date',
            field=models.DateField(blank=True, help_text='Date when processing started', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='processing_start_time',
            field=models.TimeField(blank=True, help_text='Time when processing started', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='total_time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Total time spent (alias for duration in seconds)'),
        ),
    ]
