# Generated by Django 5.0.14 on 2026-02-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_page_processing_end_date_page_processing_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='True if OCR or layout analysis is complete'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_scanned',
            field=models.BooleanField(default=False, help_text='True if the document was detected as scanned/image-based'),
        ),
    ]
