# Generated by Django 6.0.2 on 2026-03-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_page_is_processed_page_is_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='conversion_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='converted_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/converted/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='document',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/originals/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='The PDF file used for OCR/Splitting', upload_to='documents/processing/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SPLITTING', 'Splitting'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('REVIEWING', 'Reviewing'), ('COMPLETED', 'Completed'), ('CONVERTING', 'Converting'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('FAILED_VALIDATION', 'Failed Validation')], default='UPLOADED', max_length=20),
        ),
    ]
