# Generated by Django 6.0.2 on 2026-03-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_document_conversion_error_document_converted_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='The PDF file used for OCR/Splitting', null=True, upload_to='documents/processing/%Y/%m/%d/'),
        ),
    ]
