# Generated by Django 6.0.2 on 2026-03-05 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_resourceprofile_docpro_reso_is_acti_c2c01b_idx_and_more'),
        ('documents', '0023_document_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_file', models.FileField(max_length=500, upload_to='approved/%Y/%m/%d/')),
                ('final_file_size_bytes', models.BigIntegerField(default=0)),
                ('final_file_hash_sha256', models.CharField(blank=True, max_length=64)),
                ('approval_notes', models.TextField(blank=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('APPROVED', 'Approved'), ('DELIVERED', 'Delivered to Client'), ('ARCHIVED', 'Archived'), ('REVOKED', 'Approval Revoked')], db_index=True, default='APPROVED', max_length=15)),
                ('download_url', models.URLField(blank=True)),
                ('download_url_expiry', models.DateTimeField(blank=True, null=True)),
                ('delivered_to_client', models.BooleanField(default=False)),
                ('client_notified_at', models.DateTimeField(blank=True, null=True)),
                ('client_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('summary_report', models.JSONField(default=dict)),
                ('approved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approved_documents',
                'ordering': ['-approved_at'],
            },
        ),
        migrations.CreateModel(
            name='MergedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_file', models.FileField(blank=True, max_length=500, null=True, upload_to='merged/%Y/%m/%d/')),
                ('merged_file_size_bytes', models.BigIntegerField(default=0)),
                ('merged_file_hash_md5', models.CharField(blank=True, max_length=32)),
                ('page_order_manifest', models.JSONField(default=list)),
                ('total_pages_merged', models.IntegerField(default=0)),
                ('total_words', models.IntegerField(default=0)),
                ('total_processing_time', models.DurationField(blank=True, null=True)),
                ('pages_with_rejections', models.IntegerField(default=0)),
                ('unique_resources_used', models.IntegerField(default=0)),
                ('merge_status', models.CharField(choices=[('PENDING', 'Merge Pending'), ('IN_PROGRESS', 'Merge In Progress'), ('COMPLETED', 'Merge Completed'), ('FAILED', 'Merge Failed'), ('APPROVED', 'Approved by Admin'), ('DELIVERED', 'Delivered to Client')], db_index=True, default='PENDING', max_length=15)),
                ('merge_error', models.TextField(blank=True)),
                ('page_gap_errors', models.JSONField(default=list)),
                ('merge_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('merge_started_at', models.DateTimeField(blank=True, null=True)),
                ('merge_completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'merged_documents',
            },
        ),
        migrations.CreateModel(
            name='OriginalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_ref', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('original_file', models.FileField(max_length=500, upload_to='originals/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=500)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_hash_md5', models.CharField(blank=True, max_length=32)),
                ('original_format', models.CharField(choices=[('SCANNED_PDF', 'Scanned PDF'), ('READABLE_PDF', 'Readable PDF'), ('WORD_DOC', 'Word Document (.docx/.doc)'), ('CONVERTED_WORD', 'Word Converted to PDF')], default='READABLE_PDF', max_length=20)),
                ('conversion_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending Conversion'), ('CONVERTING', 'Converting...'), ('CONVERTED', 'Converted Successfully'), ('CONVERSION_FAILED', 'Conversion Failed')], default='NOT_REQUIRED', max_length=20)),
                ('converted_pdf', models.FileField(blank=True, max_length=500, null=True, upload_to='converted/%Y/%m/%d/')),
                ('conversion_error', models.TextField(blank=True)),
                ('conversion_started_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_pages', models.IntegerField(default=0)),
                ('total_words', models.IntegerField(default=0)),
                ('avg_complexity', models.CharField(blank=True, max_length=20)),
                ('pipeline_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('CONVERTING', 'Converting to PDF'), ('SPLITTING', 'Splitting Pages'), ('VALIDATING', 'Validating Pages'), ('SCORING', 'Scoring Complexity'), ('READY_TO_ASSIGN', 'Ready for Assignment'), ('ASSIGNING', 'Assigning to Resources'), ('IN_PROGRESS', 'Processing in Progress'), ('ALL_SUBMITTED', 'All Pages Submitted'), ('MERGING', 'Merging Pages'), ('MERGED', 'Merge Complete'), ('APPROVED', 'Approved by Admin'), ('REJECTED', 'Rejected'), ('FAILED', 'Pipeline Failed')], db_index=True, default='UPLOADED', max_length=25)),
                ('pipeline_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'original_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SplitPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('page_file', models.FileField(max_length=500, upload_to='split_pages/%Y/%m/%d/')),
                ('page_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='page_thumbnails/%Y/%m/%d/')),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_method', models.CharField(choices=[('NATIVE', 'Native PDF Text'), ('OCR', 'Tesseract OCR'), ('NONE', 'No Text Found')], default='NONE', max_length=20)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('blocks_json', models.JSONField(default=list)),
                ('complexity', models.CharField(choices=[('SIMPLE', 'Simple / Paragraph'), ('COMPLEX', 'Complex / Mixed'), ('TABLE_HEAVY', 'Table Heavy')], db_index=True, default='SIMPLE', max_length=15)),
                ('complexity_weight', models.FloatField(default=1.0)),
                ('complexity_scored_at', models.DateTimeField(blank=True, null=True)),
                ('table_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('block_density', models.FloatField(default=0.0)),
                ('max_processing_time', models.IntegerField(default=600)),
                ('validation_status', models.CharField(choices=[('PENDING_VALIDATION', 'Pending'), ('VALIDATION_IN_PROGRESS', 'In Progress'), ('VALIDATED', 'Validated'), ('VALIDATION_FAILED', 'Failed'), ('NEEDS_REUPLOAD', 'Needs Reupload')], db_index=True, default='PENDING_VALIDATION', max_length=25)),
                ('validation_checks', models.JSONField(default=dict)),
                ('validation_error', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_retries', models.IntegerField(default=0)),
                ('assignment_status', models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REASSIGNED', 'Reassigned'), ('TIMED_OUT', 'Timed Out'), ('ESCALATED', 'Escalated')], db_index=True, default='UNASSIGNED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'split_pages',
                'ordering': ['document', 'page_number'],
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='client',
        ),
        migrations.RemoveField(
            model_name='document',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='document',
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='page',
            name='docpro_page_status_9e122c_idx',
        ),
        migrations.RemoveIndex(
            model_name='page',
            name='docpro_page_current_f30a57_idx',
        ),
        migrations.RemoveIndex(
            model_name='page',
            name='docpro_page_documen_a90ec6_idx',
        ),
        migrations.AddField(
            model_name='approveddocument',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mergeddocument',
            name='merged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approveddocument',
            name='merged_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='documents.mergeddocument'),
        ),
        migrations.AddField(
            model_name='originaldocument',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.clientprofile'),
        ),
        migrations.AddField(
            model_name='originaldocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mergeddocument',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merged_document', to='documents.originaldocument'),
        ),
        migrations.AddField(
            model_name='approveddocument',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='documents.originaldocument'),
        ),
        migrations.AddField(
            model_name='splitpage',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_pages', to='documents.originaldocument'),
        ),
        migrations.DeleteModel(
            name='DocumentVersion',
        ),
        migrations.RemoveField(
            model_name='page',
            name='current_assignee',
        ),
        migrations.RemoveField(
            model_name='page',
            name='document',
        ),
        migrations.AddIndex(
            model_name='originaldocument',
            index=models.Index(fields=['doc_ref'], name='original_do_doc_ref_f5cad0_idx'),
        ),
        migrations.AddIndex(
            model_name='originaldocument',
            index=models.Index(fields=['pipeline_status'], name='original_do_pipelin_30a6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='originaldocument',
            index=models.Index(fields=['priority', 'deadline'], name='original_do_priorit_d8cf25_idx'),
        ),
        migrations.AddIndex(
            model_name='splitpage',
            index=models.Index(fields=['document', 'page_number'], name='split_pages_documen_eb198b_idx'),
        ),
        migrations.AddIndex(
            model_name='splitpage',
            index=models.Index(fields=['assignment_status'], name='split_pages_assignm_0dd7bd_idx'),
        ),
        migrations.AddIndex(
            model_name='splitpage',
            index=models.Index(fields=['validation_status'], name='split_pages_validat_b0adb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='splitpage',
            unique_together={('document', 'page_number')},
        ),
    ]
