# Generated by Django 6.0.2 on 2026-03-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_approveddocument_mergeddocument_originaldocument_and_more'),
        ('processing', '0011_pageassignment_reassignmentlog_rejectedpage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
