# Generated by Django 6.0.2 on 2026-03-05 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_resourceprofile_docpro_reso_status_a861c6_idx_and_more'),
        ('documents', '0025_delete_document_delete_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='documents/originals/%Y/%m/%d/')),
                ('file', models.FileField(blank=True, help_text='The PDF file used for OCR/Splitting', null=True, upload_to='documents/processing/%Y/%m/%d/')),
                ('converted_pdf', models.FileField(blank=True, null=True, upload_to='documents/converted/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SPLITTING', 'Splitting'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('REVIEWING', 'Reviewing'), ('COMPLETED', 'Completed'), ('CONVERTING', 'Converting'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('FAILED_VALIDATION', 'Failed Validation')], default='UPLOADED', max_length=20)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('merge_in_progress', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_error', models.TextField(blank=True, null=True)),
                ('final_file', models.FileField(blank=True, null=True, upload_to='documents/finals/%Y/%m/%d/')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
            ],
            options={
                'db_table': 'docpro_client_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('merged_file', models.FileField(upload_to='documents/versions/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'docpro_document_version',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('content_file', models.FileField(upload_to='pages/splits/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('IMPROPERLY_PROCESSED', 'Improperly Processed')], default='PENDING', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, help_text='Timestamp when page was locked to a resource', null=True)),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='pages/processed/%Y/%m/%d/')),
                ('version', models.PositiveIntegerField(default=0, help_text='Optimistic locking version')),
                ('layout_data', models.JSONField(blank=True, help_text='Reconstructed layout bounding boxes and structure', null=True)),
                ('text_content', models.TextField(blank=True, help_text='Raw extracted or edited text content', null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, help_text='When the resource first opened this page for editing', null=True)),
                ('processing_start_date', models.DateField(blank=True, help_text='Date when processing started', null=True)),
                ('processing_start_time', models.TimeField(blank=True, help_text='Time when processing started', null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, help_text='When the resource submitted this page', null=True)),
                ('processing_end_date', models.DateField(blank=True, help_text='Date when processing ended', null=True)),
                ('processing_end_time', models.TimeField(blank=True, help_text='Time when processing ended', null=True)),
                ('processing_duration_seconds', models.PositiveIntegerField(default=0, help_text='Total time spent processing this page in seconds')),
                ('total_time_spent', models.PositiveIntegerField(default=0, help_text='Total time spent (alias for duration in seconds)')),
                ('is_processed', models.BooleanField(default=False, help_text='True if OCR or layout analysis is complete')),
                ('is_scanned', models.BooleanField(default=False, help_text='True if the document was detected as scanned/image-based')),
                ('is_validated', models.BooleanField(default=False, help_text='Whether this page has passed the validation requirements')),
                ('validation_errors', models.JSONField(blank=True, help_text='List of validation failures (upload issues, formatting errors, etc.)', null=True)),
                ('complexity_type', models.CharField(choices=[('SIMPLE', 'Simple (Paragraphs)'), ('TABLE_HEAVY', 'Table-Heavy'), ('COMPLEX', 'Complex (Mixed/Dense)')], default='SIMPLE', max_length=20)),
                ('complexity_score', models.FloatField(default=1.0, help_text='Weighted complexity score (e.g. 1.0 for simple, 2.5 for tables)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'docpro_page',
                'ordering': ['document', 'page_number'],
            },
        ),
        migrations.RemoveField(
            model_name='approveddocument',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='approveddocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='approveddocument',
            name='merged_document',
        ),
        migrations.RemoveField(
            model_name='mergeddocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='mergeddocument',
            name='merged_by',
        ),
        migrations.RemoveIndex(
            model_name='originaldocument',
            name='original_do_doc_ref_f5cad0_idx',
        ),
        migrations.RemoveIndex(
            model_name='originaldocument',
            name='original_do_pipelin_30a6d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='originaldocument',
            name='original_do_priorit_d8cf25_idx',
        ),
        migrations.AlterUniqueTogether(
            name='splitpage',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='splitpage',
            name='split_pages_documen_eb198b_idx',
        ),
        migrations.RemoveIndex(
            model_name='splitpage',
            name='split_pages_assignm_0dd7bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='splitpage',
            name='split_pages_validat_b0adb1_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document'),
        ),
        migrations.AddField(
            model_name='page',
            name='current_assignee',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'RESOURCE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document'),
        ),
        migrations.DeleteModel(
            name='ApprovedDocument',
        ),
        migrations.DeleteModel(
            name='MergedDocument',
        ),
        migrations.RemoveField(
            model_name='originaldocument',
            name='client',
        ),
        migrations.RemoveField(
            model_name='originaldocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='splitpage',
            name='document',
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['document', 'status', 'page_number'], name='docpro_page_documen_a90ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status', 'locked_at'], name='docpro_page_status_9e122c_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['current_assignee', 'status'], name='docpro_page_current_f30a57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('document', 'page_number')},
        ),
    ]
