# Generated by Django 6.0.2 on 2026-03-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_document_documentversion_page_and_more'),
        ('processing', '0012_assignment_documentqueue_revisionhistory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OriginalDocument',
        ),
        migrations.DeleteModel(
            name='SplitPage',
        ),
    ]
