# Generated by Django 6.0.2 on 2026-03-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_delete_originaldocument_delete_splitpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='conversion_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('CONVERTING', 'Converting'), ('CONVERTED', 'Converted'), ('CONVERSION_FAILED', 'Conversion Failed')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='original_format',
            field=models.CharField(choices=[('SCANNED_PDF', 'Scanned PDF'), ('READABLE_PDF', 'Readable PDF'), ('WORD_DOC', 'Word Document'), ('CONVERTED_WORD', 'Converted Word')], default='READABLE_PDF', max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='complexity_scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='complexity_weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='page',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='table_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='validation_status',
            field=models.CharField(choices=[('PENDING_VALIDATION', 'Pending Validation'), ('VALIDATION_IN_PROGRESS', 'Validation In Progress'), ('VALIDATED', 'Validated'), ('VALIDATION_FAILED', 'Validation Failed'), ('NEEDS_REUPLOAD', 'Needs Re-upload')], default='PENDING_VALIDATION', max_length=30),
        ),
        migrations.AddField(
            model_name='page',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SPLITTING', 'Splitting'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('REVIEWING', 'Reviewing'), ('COMPLETED', 'Completed'), ('CONVERTING', 'Converting'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('FAILED_VALIDATION', 'Failed Validation'), ('VALIDATION_FAILED', 'Validation Failed')], default='UPLOADED', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='complexity_type',
            field=models.CharField(choices=[('SIMPLE', 'Simple (Paragraphs)'), ('COMPLEX', 'Complex (Mixed/Dense)'), ('TABLE_HEAVY', 'Table-Heavy')], default='SIMPLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('IMPROPERLY_PROCESSED', 'Improperly Processed'), ('UNASSIGNED', 'Unassigned')], default='PENDING', max_length=20),
        ),
    ]
