# Generated by Django 6.0.2 on 2026-03-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_document_conversion_status_document_original_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
