# Generated by Django 6.0.2 on 2026-03-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_document_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
        migrations.AddField(
            model_name='document',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_ref',
            field=models.SlugField(blank=True, help_text='Human-readable slug, e.g. invoice-report-2026-03', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pipeline_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pipeline_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('CONVERTING', 'Converting to PDF'), ('SPLITTING', 'Splitting Pages'), ('VALIDATING', 'Validating Pages'), ('SCORING', 'Scoring Complexity'), ('READY_TO_ASSIGN', 'Ready for Assignment'), ('ASSIGNING', 'Assigning to Resources'), ('IN_PROGRESS', 'Processing in Progress'), ('ALL_SUBMITTED', 'All Pages Submitted'), ('MERGING', 'Merging Pages'), ('MERGED', 'Merge Complete'), ('APPROVED', 'Approved by Admin'), ('REJECTED', 'Rejected'), ('FAILED', 'Pipeline Failed')], db_index=True, default='UPLOADED', max_length=25),
        ),
        migrations.AddField(
            model_name='document',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='page',
            name='complexity_type',
            field=models.CharField(choices=[('SIMPLE', 'Simple (Paragraphs)'), ('TABLE_HEAVY', 'Table-Heavy'), ('COMPLEX', 'Complex (Mixed/Dense)')], default='SIMPLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('IMPROPERLY_PROCESSED', 'Improperly Processed'), ('UNASSIGNED', 'Unassigned'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TIMED_OUT', 'Timed Out'), ('ESCALATED', 'Escalated'), ('REASSIGNED', 'Reassigned')], default='PENDING', max_length=20),
        ),
    ]
