# Generated by Django 6.0.2 on 2026-03-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_add_doc_ref_pipeline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_ref',
            field=models.SlugField(blank=True, help_text='Human-readable slug, e.g. invoice-report-2026-03', max_length=80, null=True, unique=True),
        ),
    ]
