# Generated by Django 6.0.2 on 2026-03-07 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_make_doc_ref_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_id', models.CharField(help_text='Identifier from OCR/Layout analysis', max_length=100)),
                ('extracted_text', models.TextField(blank=True, help_text='Original text from OCR')),
                ('current_text', models.TextField(blank=True, help_text='Latest user edit')),
                ('bbox', models.JSONField(help_text='Bounding box [x0, y0, x1, y1]')),
                ('font_size', models.FloatField(default=10.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='documents.page')),
            ],
            options={
                'db_table': 'docpro_block',
                'ordering': ['page', 'id'],
                'unique_together': {('page', 'block_id')},
            },
        ),
        migrations.CreateModel(
            name='BlockEdit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('page_num', models.IntegerField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='documents.block')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docpro_block_edit',
                'ordering': ['-saved_at'],
            },
        ),
    ]
