# Generated by Django 6.0.2 on 2026-03-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_block_blockedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='font_color',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='block',
            name='font_name',
            field=models.CharField(default='Helvetica', max_length=100),
        ),
    ]
