# Generated by Django 6.0.2 on 2026-03-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_block_font_color_block_font_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='conversion_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='conversion_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
