# Generated by Django 6.0.2 on 2026-03-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_document_deleted_at_document_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='conversion_method',
            field=models.CharField(blank=True, choices=[('LIBREOFFICE', 'LibreOffice'), ('DOCX2PDF', 'docx2pdf')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='converted_file_hash_md5',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='converted_file_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
