# Generated by Django 6.0.2 on 2026-03-08 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_document_celery_task_id_document_conversion_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['y', 'x']},
        ),
        migrations.AddField(
            model_name='block',
            name='block_index',
            field=models.IntegerField(default=0, help_text='Index in extraction order'),
        ),
        migrations.AddField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('text', 'Plain Text'), ('table_cell', 'Table Cell'), ('header', 'Header'), ('footer', 'Footer'), ('caption', 'Caption')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='block',
            name='col_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='font_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italic')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='block',
            name='font_weight',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='block',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='row_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='table_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='block',
            name='width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='page',
            name='blocks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='blocks_extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='has_tables',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='pdf_page_height',
            field=models.FloatField(default=842.0, help_text='PDF page height in points (A4 default)'),
        ),
        migrations.AddField(
            model_name='page',
            name='pdf_page_width',
            field=models.FloatField(default=595.0, help_text='PDF page width in points (A4 default)'),
        ),
        migrations.AlterField(
            model_name='block',
            name='bbox',
            field=models.JSONField(blank=True, help_text='Bounding box [x0, y0, x1, y1]', null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='font_color',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.CreateModel(
            name='PageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_ref', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('row_count', models.IntegerField(default=0)),
                ('col_count', models.IntegerField(default=0)),
                ('table_json', models.JSONField(default=list)),
                ('has_borders', models.BooleanField(default=True)),
                ('has_header', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='documents.page')),
            ],
            options={
                'db_table': 'docpro_page_table',
                'ordering': ['y', 'x'],
            },
        ),
    ]
