# Generated by Django 6.0.2 on 2026-03-08 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_alter_block_options_block_block_index_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block',
            name='original_text',
            field=models.TextField(blank=True, help_text='OCR/native text — NEVER modified'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['page', 'block_id'], name='docpro_bloc_page_id_bbff1e_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['page', 'block_type'], name='docpro_bloc_page_id_a71412_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['table_id'], name='docpro_bloc_table_i_b497a8_idx'),
        ),
    ]
