# Generated by Django 6.0.3 on 2026-03-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_block_last_edited_at_block_last_edited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='block_density',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='page',
            name='image_density',
            field=models.FloatField(default=0.0),
        ),
    ]
