# Generated by Django 6.0.3 on 2026-03-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_page_block_density_page_image_density'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='split_error',
            field=models.TextField(blank=True, default='', help_text='Errors encountered during PDF splitting'),
        ),
    ]
