# Generated by Django 5.0.14 on 2026-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminprofile_clientprofile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resourceprofile',
            index=models.Index(fields=['is_active_for_assignment', '-priority', 'id'], name='docpro_reso_is_acti_c2c01b_idx'),
        ),
    ]
