# Generated by Django 6.0.2 on 2026-03-03 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'docpro_organization',
            },
        ),
        migrations.RenameField(
            model_name='resourceprofile',
            old_name='default_page_capacity',
            new_name='max_capacity',
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='avg_processing_time',
            field=models.FloatField(default=0.0, help_text='Average processing time in seconds'),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='accounts.organization'),
        ),
    ]
