# Generated by Django 6.0.2 on 2026-03-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprofile',
            name='rejection_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of assignments rejected for this resource'),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='reliability_score',
            field=models.FloatField(default=100.0, help_text='Resource quality score (0-100)'),
        ),
    ]
