# Generated by Django 6.0.2 on 2026-03-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_resourceprofile_rejection_count_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resourceprofile',
            name='docpro_reso_is_acti_c2c01b_idx',
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='current_load',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BUSY', 'Busy')], default='INACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='resourceprofile',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10, help_text='Max pages assignable at once'),
        ),
        migrations.AlterField(
            model_name='resourceprofile',
            name='reliability_score',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddIndex(
            model_name='resourceprofile',
            index=models.Index(fields=['status', 'is_available'], name='docpro_reso_status_a861c6_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceprofile',
            index=models.Index(fields=['last_active_at'], name='docpro_reso_last_ac_c2f3a7_idx'),
        ),
        migrations.RemoveField(
            model_name='resourceprofile',
            name='avg_processing_time',
        ),
        migrations.RemoveField(
            model_name='resourceprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='resourceprofile',
            name='is_active_for_assignment',
        ),
        migrations.RemoveField(
            model_name='resourceprofile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='resourceprofile',
            name='rejection_count',
        ),
    ]
