# Generated by Django 6.0.2 on 2026-03-05 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_resourceprofile_docpro_reso_is_acti_c2c01b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resourceprofile',
            name='docpro_reso_status_a861c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='resourceprofile',
            name='docpro_reso_last_ac_c2f3a7_idx',
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='avg_processing_time',
            field=models.FloatField(default=0.0, help_text='Average processing time in seconds'),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='is_active_for_assignment',
            field=models.BooleanField(default=True, help_text='If False, no new pages will be assigned'),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='rejection_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of assignments rejected for this resource'),
        ),
        migrations.AlterField(
            model_name='resourceprofile',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10, help_text='Default max pages per cycle'),
        ),
        migrations.AlterField(
            model_name='resourceprofile',
            name='reliability_score',
            field=models.FloatField(default=100.0, help_text='Resource quality score (0-100)'),
        ),
        migrations.AddIndex(
            model_name='resourceprofile',
            index=models.Index(fields=['is_active_for_assignment', '-priority', 'id'], name='docpro_reso_is_acti_c2c01b_idx'),
        ),
        migrations.RemoveField(
            model_name='resourceprofile',
            name='current_load',
        ),
        migrations.RemoveField(
            model_name='resourceprofile',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='resourceprofile',
            name='last_active_at',
        ),
        migrations.RemoveField(
            model_name='resourceprofile',
            name='last_login_at',
        ),
        migrations.RemoveField(
            model_name='resourceprofile',
            name='status',
        ),
    ]
