# Generated by Django 6.0.2 on 2026-03-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_resourceprofile_docpro_reso_status_a861c6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprofile',
            name='current_load',
            field=models.IntegerField(default=0, help_text='Number of pages currently assigned'),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BUSY', 'Busy')], default='INACTIVE', max_length=20),
        ),
    ]
