# Generated by Django 6.0.2 on 2026-03-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_resourceprofile_current_load_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceprofile',
            name='current_load',
            field=models.IntegerField(default=0, help_text='Pages currently assigned to this resource'),
        ),
        migrations.AlterField(
            model_name='resourceprofile',
            name='is_available',
            field=models.BooleanField(default=False, help_text='True when resource is online and available for assignment'),
        ),
        migrations.AlterField(
            model_name='resourceprofile',
            name='last_active_at',
            field=models.DateTimeField(blank=True, help_text='Updated every 5 min via heartbeat', null=True),
        ),
        migrations.AlterField(
            model_name='resourceprofile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last login', null=True),
        ),
        migrations.AlterField(
            model_name='resourceprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active — online and available'), ('INACTIVE', 'Inactive — offline or no heartbeat'), ('BUSY', 'Busy — at capacity')], db_index=True, default='INACTIVE', help_text='ACTIVE=online, INACTIVE=offline, BUSY=at capacity', max_length=10),
        ),
    ]
