# Generated by Django 6.0.2 on 2026-03-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_resource_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceprofile',
            name='current_load',
        ),
        migrations.AlterField(
            model_name='resourceprofile',
            name='max_capacity',
            field=models.FloatField(default=10.0, help_text='Default max pages per cycle'),
        ),
    ]
