# Generated by Django 6.0.2 on 2026-03-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_resourceprofile_current_load_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='last_seen_page',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
